---
# It will be used as the Internal dns domain name if DNS is enabled.
# Services will be discoverable under
# <service-name>.<namespace>.svc.<domainname>.<clustername>, e.g.
# myservice.default.svc.k8s.cluster
k8s_domain_name: k8s
k8s_cluster_name: cluster

# A service account's credentials include a generated email address that is unique.
# Specify the email address of the user account
# You can create one according to the procedure specified in this reference
# https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount
gce_service_account_email: '...-compute@developer.gserviceaccount.com'

# The full path of your unique service account credentials file. 
# Details on generating this can be found at
# https://docs.ansible.com/ansible/guide_gce.html#credentials
# You can download json credentials according to the procedure specified in this reference
# https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts
gce_credentials_file: '{{ ansible_env.HOME }}/gcloud.json'

# Specify your project ID which one used from your GCP account
gce_project_id: my-project-id

# The network determines what network traffic the instance can access
# Use auto generated network name in most of all cases
gce_network_name: '{{ k8s_domain_name }}'

# Assigns the instance an IPv4 address from the subnetwork’s range.
# Use auto generated subnetwork name in most of all cases
gce_subnet_name: '{{ gce_network_name }}-{{ k8s_cluster_name }}'

# A region is a specific geographical location where you can run your resources.
# Each region has one or more zones.
gce_instances_region: europe-west1

# A zone is an isolated location within a region.
# Resources that live in a zone, such as instances,
# are referred to as zonal resources
gce_instances_zone: europe-west1-b

# Kubernetes service API port and health check port
k8s_api_port: 443
k8s_api_health_check_port: 8080

# User services port and health check port
k8s_services_port: 443
k8s_health_check_port: 80

# It should be an IP addresses range corresponed with zone, e.g.
# Western Europe Zone has 10.132.0.0/20 IP range
# Use default IP range for determined zone in most of all cases
gce_instances_ip_range: 10.132.0.0/24

# Flannel internal overlay network. It will assign IP
# addresses from this range to individual pods.
# This network must be unused block of space.
k8s_flannel_network: 10.20.0.0/16

# Google load balancer network
k8s_lb_network: 130.211.0.0/22

# Google health checker network
k8s_health_checker_network: 35.191.0.0/16
