---
# Using of network storage
# If network storage disabled will use local disk for every requested claim 
network_storage: false

# Kubernetes network persistent disk type, valid values: `gce`, `ceph`
# TODO: AWS persistent disk `aws`
network_storage_type: gce 

# Additional Kubernetes namespaces
k8s_namespaces:
  - dev

# Users access data
k8s_admin_username: admin
k8s_release_username: release
k8s_guest_username: guest

# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_policy_dir: '{{ k8s_conf_dir }}/policy'

# Master hosts nsmes
k8s_master_hosts: {}

# SSL base certificate name
# SSL folder and file names will use the same name
ssl_name: kubernetes

# Path to files with SSL certificates and keys
ssl_dir: /etc/ssl/{{ ssl_name }}

# Ceph user token
# ceph auth print-key client.admin | base64
ceph_user_token: 'ceph user token here'

# SSL certificate and private key for running user services into Kubernetes
k8s_services_cert: |
  ----BEGIN CERTIFICATE----
  - Your certificate here -
  -----END CERTIFICATE-----
k8s_services_cert_key: |
  ----BEGIN PRIVATE KEY----
  - Your private key here -
  -----END PRIVATE KEY-----
