---
- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'

- name: Helm tiller
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - helm-tiller.yaml

- name: Deploy script for tiller
  template:
    src: deploy-tiller.sh
    dest: "{{ k8s_addons_dir }}/deploy-tiller.sh"
    mode: 0755

- name: Run deploy script for tiller
  command: "{{ k8s_addons_dir }}/deploy-tiller.sh"
  when: inventory_hostname in k8s_master_hosts[0]
