---
# Kubernetes configs path
k8s_conf_dir: /etc/kubernetes
k8s_addons_dir: '{{ k8s_conf_dir }}/addons'

# Master hosts nsmes
k8s_master_hosts: {}

# Kube Lego image
k8s_kube_lego_image: jetstack/kube-lego
k8s_kube_lego_image_tag: 0.1.5
