apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: {{ k8s_hyperkube_image }}:{{ k8s_hyperkube_image_tag }}
    command:
    - /hyperkube
    - controller-manager
    - --allocate-node-cidrs=true
    - --cluster-cidr={{ k8s_cluster_cidr }}
    - --cluster-signing-cert-file={{ ssl_dir }}/ca.pem
    - --cluster-signing-key-file={{ ssl_dir }}/ca-key.pem
    - --controllers=*
    - --feature-gates=AllAlpha=false
    - --master=https://127.0.0.1:{{ k8s_api_port }}
    - --kubeconfig={{ k8s_policy_dir }}/controller.kubeconfig
    - --leader-elect=true
    - --root-ca-file={{ ssl_dir }}/ca.pem
    - --service-account-private-key-file={{ ssl_dir }}/master-key.pem
    - --service-cluster-ip-range={{ k8s_services_network }}
    - --use-service-account-credentials
    - --v={{ k8s_log_level }}
    - --vmodule={{ k8s_log_spec }}
    resources:
      requests:
        cpu: 200m
    livenessProbe:
      httpGet:
        path: /healthz
        host: 127.0.0.1
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: policy
      mountPath: {{ k8s_policy_dir }}
      readOnly: true
    - name: certificates
      mountPath: {{ ssl_dir }}
      readOnly: true
  volumes:
  - name: policy
    hostPath:
      path: {{ k8s_policy_dir }}
  - name: certificates
    hostPath:
      path: {{ ssl_dir }}
