---

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-inject
  namespace: {{ k8s_istio_namespace }}
data:
  config: |-
    policy: "disabled"
    namespaces: [""] # everything, aka v1.NamepsaceAll, aka cluster-wide
    initializerName: "sidecar.initializer.istio.io"
    params:
      initImage: {{ k8s_istio_proxy_init_image }}:{{ k8s_istio_proxy_init_image_tag }}
      proxyImage: {{ k8s_istio_proxy_image }}:{{ k8s_istio_proxy_image_tag }}
      verbosity: {{ k8s_log_level }}
      version: {{ istio_version }}
      meshConfigMapName: istio
      imagePullPolicy: IfNotPresent

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: istio-initializer
  namespace: {{ k8s_istio_namespace }}
  annotations:
    sidecar.istio.io/inject: "false"
  initializers:
    pending: []
  labels:
    istio: istio-initializer
spec:
  replicas: 1
  template:
    metadata:
      name: istio-initializer
      labels:
        istio: initializer
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-initializer
      containers:
        - name: initializer
          image: {{ k8s_istio_sidecar_initializer_image }}:{{ k8s_istio_sidecar_initializer_image_tag }}
          imagePullPolicy: IfNotPresent
          args:
            - --port=8083
            - --namespace={{ k8s_istio_namespace }}
            - -v=2
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
      volumes:
      - name: config-volume
        configMap:
          name: istio

---

apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: istio-sidecar
initializers:
  - name: sidecar.initializer.istio.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
          - statefulsets
          - jobs
          - daemonsets
