---
- hosts: master
  remote_user: '{{ k8s_ssh_user }}'
  become: true
  roles:
    - readiness
    - role: ingress
      k8s_master_hosts: '{{ groups["master"] }}'
      k8s_node_hosts: '{{ groups["node"] }}'
