
- hosts:
    - master
    - node
  remote_user: '{{ k8s_ssh_user }}'
  become: true
  roles:
    - role: user
      k8s_master_hosts: '{{ groups["master"] }}'

- hosts:
    - master
    - node
  remote_user: '{{ k8s_ssh_user }}'
  roles:
    - role: user
      k8s_master_hosts: '{{ groups["master"] }}'
