---
- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'

- name: Kube Lego
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - kube-lego.yaml

- name: Deploy script for Kube Lego
  template:
    src: deploy-kubelego.sh
    dest: "{{ k8s_addons_dir }}/deploy-kubelego.sh"
    mode: 0755

- name: Run deploy script for Kube Lego
  command: "{{ k8s_addons_dir }}/deploy-kubelego.sh"
  when: inventory_hostname in k8s_master_hosts[0]
