---
# A service account's credentials include a generated email address that is unique.
# Specify the email address of the user account
# You can create one according to the procedure specified in this reference
# https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount
gce_service_account_email: '...-compute@developer.gserviceaccount.com'

# The full path of your unique service account credentials file. 
# Details on generating this can be found at
# https://docs.ansible.com/ansible/guide_gce.html#credentials
# You can download json credentials according to the procedure specified in this reference
# https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts
gce_credentials_file: '{{ ansible_env.HOME }}/gcloud.json'

# Specify your project ID which one used from your GCP account
gce_project_id: my-project-id

# A zone is an isolated location within a region.
# Resources that live in a zone, such as instances,
# are referred to as zonal resources
gce_instances_zone: europe-west1-b

# Size of network persistent disk in Gb
network_storage_size: 100

# Name of GCE persistent disk
gce_storage_name: pd-std

# Type of GCE storage, options: `slow`, `fast`
gce_storage_type: slow

gce_disk_type: '{% if gce_storage_type == "slow" %}pd-standard{% else %}pd-ssd{% endif %}'
