---
- name: Check addons directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ k8s_addons_dir }}'

- name: Statistics services
  template:
    src: "{{ item }}"
    dest: "{{ k8s_addons_dir }}/{{ item }}"
  with_items:
    - heapster.yaml

- name: Deploy script for statistics services
  template:
    src: deploy-stats.sh
    dest: "{{ k8s_addons_dir }}/deploy-stats.sh"
    mode: 0755

- name: Run deploy script for stats
  command: "{{ k8s_addons_dir }}/deploy-stats.sh"
  when: inventory_hostname in k8s_master_hosts[0]
